version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_compose:/var/jenkins_home
      - ./run/docker.sock:/var/run/docker.sock
    networks:
      - some-net
  

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - jenkins
    environment:
      - DOMAIN=localhost
      - PORT=8080
    depends_on:
      - jenkins
    networks:
      - some-net

networks:
  some-net:
    driver: bridge
