pipeline {
    agent { 
        node {
            label 'docker-agent-python'
            }
      }
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                cd LearnJenKins
                cd myapp
                pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                cd LearnJenKins
                cd myapp
                python3 hello.py
                python3 hello.py --name=Brad
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                docker build --pull --rm -f "LearnJenKins\\myapp\\Dockerfile" -t flash-docker "LearnJenKins\\myapp" 
                docker run -d -p 5000:5000 --network learnjenkins_jenkins flash-docker
                '''
            }
        }
    }
}